### ISSUE TITLE
make -K default?

### ISSUE THREAD

**Issue by gniquil** [anmonteiro/lumo#16]
Is there a reason why not? It makes 99% use case faster.

**Comment by anmonteiro** [comment]
This needs some more thought.

Personally I don't like it because:
- it may mask problems when actively developing a namespace (where it doesn't update the latest changes because there's a cached version)
- it's too implicit which may generate a lot of confusion to people starting out.
- if you really want it you can easily add a shell alias


That said, I'm interested in hearing more feedback that the community might have and factor that into a final decision.

**Comment by gniquil** [comment]
Ok sounds good.
