### ISSUE TITLE
TCP Socket REPL

### ISSUE THREAD

**Issue by jmfirth** [anmonteiro/lumo#22]
I wanted to open an issue to discuss and track efforts for implementing a TCP socket REPL, in the vein of Planck's REPL, for Lumo.

**Comment by jmfirth** [comment]
I have made a rough prototype of this in a branch in my fork [feature/socket-repl](https://github.com/jmfirth/lumo/tree/feature/socket-repl).

This currently is hardcoded to `127.0.0.1:5555`.  You can connect to it from `inf-clojure` if you set `(setq inf-clojure-program '("localhost" . 5555))`.

[Demo](https://dl.dropboxusercontent.com/u/15438741/lumo-socket-repl-demo.gif)

**Comment by mfikes** [comment]
This is cool stuff! One thing to consider is "socket REPL isolation" (keeping `*1` _etc._ separate per season). In ClojureScript we don't have it as easy as in Clojure where you can rely on dynamic binding. In Planck I took an approach of "context switching," for lack of a better way to describe it.

**Comment by anmonteiro** [comment]
Wow, this is great!
For a first pass it may be OK to skip @mfikes's suggestion as we don't implement `*1`, `pst` et. al.
Is there any other uses for said session/context switching?

@jmfirth do you want to put together a PR so that we can iterate on this?

**Comment by mfikes** [comment]
For reference, here are the vars that Planck context switches for Socket REPL isolation (I believe these are faithful to Clojure's Socket REPL implementation): https://github.com/mfikes/planck/blob/78265343b531346baf663c4051a31b5ec2f8773e/planck-cljs/src/planck/repl.cljs#L1421-L1432

**Comment by mfikes** [comment]
A bit more info on the context switching (in case it is useful at the point Lumo considers something similar):

I believe Clojure leverages the thread-local nature of dynamic vars, with the necessary set bound on the socket REPL server thread, thus keeping any changes to them separate from other socket REPL threads. Since we don't have this in ClojureScript, simply "context switching" provides a close approximation.

But, another thing that might _not_ be faithful to Clojure is the case that callbacks occur later, after the context switch has replaced things. I haven't looked at this in a while, but it is one area where context switching gets you pretty close to Clojure's behavior (and perhaps close enough), but truth be told, it is not exactly the same thing.

**Comment by jmfirth** [comment]
@mfikes your implementation in Planck should definitely be the reference we strive for, to my mind.  I don't have near the experience of REPL development as I wish I did, so keeping these kinds of things in mind is very useful to me.

@anmonteiro sounds great,  I coded this quickly this morning and had to leave, but I'll get it cleaned up a bit and submit a consolidated PR of the changes in a few hours time (I hope).

Thanks to both of you for the feedback!  I'm really excited to see this feature come to life.

**Comment by anmonteiro** [comment]
Just leaving this here too: 
[Planck's Socket REPL support commit](https://github.com/mfikes/planck/commit/ca687dda38e893a4c7c4c3bc58c1c2f8eee72a52)

**Comment by mfikes** [comment]
The equivalent (actually simpler) commit for Socket REPL support in C (the previous was Objective C) is https://github.com/mfikes/planck/commit/e023b2780070f64928d731ff2870dd44342d17f6

**Comment by jmfirth** [comment]
Pretty close now to basic functionality.  Here's a [demo](https://dl.dropboxusercontent.com/u/15438741/lumo-socket-eval-buffer.gif) of evaluating a CLJS buffer with `inf-clojure`, printing the contents of `package.json`..

**Comment by anmonteiro** [comment]
fixed https://github.com/anmonteiro/lumo/commit/04075c735aa26eac723276fb55c7eeec50c15e1c
