### ISSUE TITLE
How to compile Macchiato project with lumo?

### ISSUE THREAD

**Issue by salmazov** [anmonteiro/lumo#289]
Macchiato framework has a difficult config file. And I tried to use lumo to compile project, but 'there are no namespace' errors.

How to build Macchiato web app (lein new macchiato myapp) with lumo?

**Comment by anmonteiro** [comment]
I never used Macchiato. @yogthos can you help?

**Comment by yogthos** [comment]
It should just be a matter of using the [cljs compiler config](https://github.com/macchiato-framework/macchiato-template/blob/cf0db28536b10dcc20e6d37d62c003b9c276c83f/resources/leiningen/new/macchiato/project.clj#L61) from project.clj. However, I'm not sure how practical it would be as the development workflow relies on Figwheel reloading.

**Comment by anmonteiro** [comment]
Right, I guess there is an expectations problem here. 

@salmazov:
Lumo doesn't read any `project.clj` files or attempts to resolve/download dependencies. They need to be explicitly passed in.

So while you can probably bootstrap your Macchiato project with `lein`, you'll need to assemble a classpath and call the `lumo.build.api` yourself.

I'm closing this because it's not an issue in Lumo. Let me know if you have further questions.
