### ISSUE TITLE
Support for custom data_readers.cljc file in Lumo?

### ISSUE THREAD

**Issue by didibus** [anmonteiro/lumo#388]
I'm trying to have custom tagged literals in ClojureScript, and it seems I can't get the `data_readers.cljc` file to work with Lumo. Is it not supported?

Thanks

**Comment by arichiardi** [comment]
It should be, @anmonteiro might know better, do you have an example of what is not working?

**Comment by didibus** [comment]
Clojure complains that no data reader exists for a given tag. If I use the clojurescript Java compiler, it doesn't. So I was assuming it is because with Lumo, the file wasn't picked up at all, or parsed.

**Comment by arichiardi** [comment]
Note that lumo is self-host so no Java can be ever evaluated.
Having said that, it can be that some problem is in the air, it would be great to have a stacktrace of the porblem or even better a repro.

I keep a reporistory only for those here: https://github.com/arichiardi/lumo-repros

I can make you contributor if you want to as well so that it is easy to hack on a PR.

**Comment by anmonteiro** [comment]
This issue is at risk of being closed for lack of sufficient information. Please provide a simple example with detailed steps to reproduce the problem.

The data reader functionality should work in Lumo.

**Comment by arichiardi** [comment]
I tried to have a look at the tests but the data reader ones have not been ported. I will make sure they are ported in a PR so that at least we can see if those pass.
