### ISSUE TITLE
Documentation for dependency inclusion

### ISSUE THREAD

**Issue by royaldark** [anmonteiro/lumo#51]
First off, kudos on the great work on this project! I love Clojure, but needing the JVM for ClojureScript has been very offputting.

Is there any documentation for how to include dependencies? From looking around, it seems like Lumo supports both Node packages, as well as some lein-sourced packages?

It would be nice to have this information in the readme so people can get up and running quickly.

**Comment by anmonteiro** [comment]
I'm planning on creating a documentation website for Lumo, but hadn't had the time to do it so far.

Meanwhile, here's how dependencies work in Lumo:

### ClojureScript dependencies

Lumo supports a `-c / --classpath` command line option which allows you to specify a (artificial) classpath where Lumo will look for dependencies. This colon-separated classpath (or semi-colon separated path for windows users) can include both JAR files and filesystem directories. Below is an example.

Given the following directory tree:

```
├── src
│   ├── foo
│   │   ├── core.cljs
│   │   └─ bar.cljs
```

you could require `foo.core` and `foo.bar` by starting lumo like this: 

```shell
$ lumo -c src
```

### JavaScript dependencies

JavaScript dependencies from Node modules can be imported to a project like you'd do in a Node.js context. So if you, e.g. `npm install left-pad` locally, it'll create a `node_modules` folder in the directory you ran the `npm` command from. 
Starting Lumo from that same directory, you can then `(def left-pad (js/require "left-pad"))` and use the module.

**Note**: no special command line option is required for Lumo to see these dependencies. Because it implements the Node.js module resolution algorithm, Lumo will automatically look for them in the `node_modules` folder. The same applies for globally installed modules.

**Comment by royaldark** [comment]
This is great, thanks!

**Comment by honzabrecka** [comment]
Thank you for this! Is there a way how one can use Closure Library (eg. `goog.Uri`)?

**Comment by eginez** [comment]
also there https://github.com/eginez/calvin,  that will boostraped a lumo repl with dependencies coming from a lein file

**Comment by rberger** [comment]
One idea: How about setting up a wiki with the repo and allowing pull requests for documentation from the folks who have the time to do something? I would be glad to contribute. The community could help vet and improve the documentation as it goes.

Here are some of the things that I as a Clojurescript and Lumo noobie wished I had for being able to use Clojurescript to replace shell scripts (much of this I did figure out but it was not easy):

- [ ] How to figure out / find what clojure/clojurescript libraries can work with lumo
- [ ]  Detailed npm interop usage examples of how to: 
  * Get the library into the project
  * Require and use of npm libraries. 
     * I.E. converting the npm library JS signatures into clojurescript signatures
- [ ]  How to deal with node libraries that only did async (callback) results
  * The basics
    * Need to use [andare](https://github.com/mfikes/andare) jar and not the `clojure.core.async` jar
    * Wrapping the call and use in core.async go blocks
    * Realizing that Clojurescript core.async does not support blocking core.async functions
    * `promise` / `deliver` from Clojure doesn't work in Clojurescript
  * Patterns to allow one to encapsulate npm library functionality in normally usable Clojurescript functions
    * I never figured out how to do this
- [ ] How to do I/O (`slurp` and `spit` at least) and `shelling out` 
- [ ] How to write tests for lumo scripts
- [ ] How to take a Lumo script and turn it into a publishable NPM package
  * How to get Clojurescript libraries into the repo/package
    * How to set up the command line to use those libraries
    * How to set up the package.json to incorporate them
  * How to create a bin bash, clojurescript or JS as the executable that launches the script from a shell
    * Would need to work from within the development repo as well as after its installed via `npm install -g`
      * Generate the right paths for the lumo executable, the source files and dependencies within the package

And probably the biggest help would be to as many examples (or pointers to examples) of working scripts and projects. Its really hard to find any examples. Ideally some examples that show how to do things end to end, how to package, etc. I tried to do that with my projects so far (though I don't know if they are _good_ examples!) 
* https://github.com/rberger/lumo-npm-example
* https://github.com/omnypay/semver-from-git

**Comment by anmonteiro** [comment]
Feel free to PR to the `site` branch on this repo. I've started working on some things under the `docs` folder

**Comment by d9k** [comment]
Please, update the docs with info about including dependencies! I had to find this issue to understand how to do it.

**Comment by arichiardi** [comment]
The wiki is available now for folks to contribute!

https://github.com/anmonteiro/lumo/wiki

Info about how to use dependencies, both coming from maven and npm, have been included there. Closing this one for now but feel free to open others PRs for addressing particular areas of the docs.

**Comment by johanatan** [comment]
I'm finding that lumo isn't finding the globally installed version of `xmlhttprequest@1.8.0` that I have. If, however, I `npm install` it locally in the directory i'm running `lumo` from, it works fine.

Is this a known issue/limitation?

**Comment by anmonteiro** [comment]
@johanatan you may have to set `NODE_PATH` in your env
