### ISSUE TITLE
Option to cache only libraries?

### ISSUE THREAD

**Issue by jiyinyiyong** [anmonteiro/lumo#54]
As I'm trying cache in my project I found caching libraries is quite necessary while caching my code breaks my `(require 'x.y.z :reload)` code. So I guess that might be how I use caches:

* generate caches for libraries
* run REPL and load the main file
* reload changed file via REPL(no cache for them, so loads new files)
* when dependencies change, regenerate libraries caches

How do you use caches? Is such an option useful for your cases?

----

Update: I mean libraries in jar files with versions. I figured out Lumo caches code in my `src/` folder too when I added them into classpath. I want code `src/` not cached during development.

**Comment by jjl** [comment]
I'm finding cacheing to be full of bugs at the minute, to the degree that I find myself clearing out the cache more often than not. What do you mean by cacheing libraries is "quite necessary"?

**Comment by jiyinyiyong** [comment]
In my case caching is quite useful. I didn't see many bugs.

In my code I got quite some libraries in order to run the project. Compiling them every time makes it really slow. So in my case they are good to be cached.

**Comment by jiyinyiyong** [comment]
How about this? Since the caches is related to the content of the file, the files is stored with a name, which is hard to figure out if the cache is outdated:

```bash
cljs_SLASH_core_SLASH_async_SLASH_impl_SLASH_timers.js
```

If we can append the filename with a MD5 checksum of the file content, then it's easier to find out if caches is outdated:

```
cljs_SLASH_core_SLASH_async_SLASH_impl_SLASH_timers-<file-md5>.js
```

Then changed files are just recognized and compilation would be chosen.

**Comment by anmonteiro** [comment]
I'm thinking that perhaps a better alternative would be to invalidate a cache via last modified timestamps. I think this is how Planck does it, and we avoid calculating potentially expensive hashes everytime we're requiring a namespace.

**Comment by jiyinyiyong** [comment]
That would be also cool. I didn't notice Planck has caching BTW 😄

**Comment by kkinnear** [comment]
I agree that invalidating a cache via a last modified timestamp is probably a reasonable thing to do, and is also what I think I remember planck does.   A hash seems like a bit much, particularly  since I'm attracted to lumo based on its quick startup and execution environment.

An interesting question is: when do you check the timestamps to invalidate the cache?

I'm thinking that `(require <ns> :reload)` would not be one of those times.  If I tell you to reload it, I think I want you to reload it regardless of the timestamps.  That would mimic the basic Clojure REPL behavior, as far as I know.

Seems like you'd check the timestamps when you started up lumo and were loading things initially, and maybe you'd check the timestamps for a regular `(require <ns>)`.  I don't know what planck does in that case, since I only ever type `(require <ns>)` once when I start a REPL.  I always type
`(require <ns> :reload)` after that when I've changed a source file.  

Of course, at a Clojure REPL if you type `(require <ns>)` and it is already loaded, I don't think anything happens.  So maybe you wouldn't want to do any cache invalidation on a bare `(require <ns>)` after all, since I assume that you are trying to mimic the behavior of a Clojure REPL, to minimize the surprise factor.   Maybe you only check the timestamps on startup and when a `(require <ns>)` actually does something (because the `<ns>` is not already loaded).

But it seems pretty clear to me that, regardless of the timestamps, if I say `(require <ns> :reload)` that you should invalidate the cache and recompile the file and cache the new results (assuming of course that the cache is in use at all).

**Comment by anmonteiro** [comment]
I think you're conflating 2 things. There are 2 different levels of abstraction here. One is the abstraction provided by `require`. The other is related to how we load files.

What I meant above, and it may not be clear immediately, is that by invalidating the cache with last modified timestamps, `require :reload` will just work. If you `require` without `:reload` after a file has been required it won't do anything anyway, but that's because of how the semantics of `require` work.

There's no need for any complex stuff here. Just check last modified timestamps when loading a file.

**Comment by kkinnear** [comment]
I can see what you mean about loading files and `require` being different.  So you are saying if I say `(require <ns> :reload)`, then you will try to load the file.  The file loader will check the file timestamp and if it hasn't changed since the cached file(s) were created, then you will reload the cached file and not compile and cache a new file?  I can see where that would make sense.

**Comment by anmonteiro** [comment]
Yes, that's what I mean. I think it's simple and effective. Do you see any drawbacks of using that approach?

**Comment by kkinnear** [comment]
No, I think that will work fine.  In the unlikely event someone *really* needs to load an older file or the timestamps have gotten messed up, they can always invalidate the cache by hand like I am already doing.  There isn't much point in doing something more complex to handle an edge condition that is unlikely to come up.  Sounds good to me!  Thanks!

**Comment by jiyinyiyong** [comment]
Some context at https://github.com/anmonteiro/lumo/commit/ed60f0587688ba686e233a3b89b062a6435497d9#commitcomment-22128792

When I actually inserted logs in the code and run, I found the suggestion for logs somehow useless. When I use `(require 'x :reload)`, it just skips the caches. So this piece of code only have impacts on initializations, which does not need logs. Or only print logs with `util/debug-prn`?

**Comment by anmonteiro** [comment]
I don't agree. I think it would still print cache invalidation logging even if you `require :reload`

**Comment by jiyinyiyong** [comment]
I tried to run the code with my logs but I'm not sure. Here are my guesses:

```
(defn- cached-callback-data
  [cache-dir cache-prefix source-data]
  (when-not (nil? cache-dir)
    (let [cache-filename (str cache-prefix JS_EXT)
          cached-data (js/$$LUMO_GLOBALS.readCache cache-filename)]
```

* run `require` with `:reload`, `cached-data` is `nil`
* run `lumo -i`, cache-data, `cached-data` is sometimes something that we can compare modified time

So it seems caches is just ignored when `(require 'x :reload)` is called. Not very sure if that's correct or not.
