### ISSUE TITLE
lumo not support `defmacro` in `cljc` file

### ISSUE THREAD

**Issue by gfZeng** [anmonteiro/lumo#57]
- `foo/bar.cljc`
```clojure
(ns foo.bar)

#?(:clj (defmacro koo [x] ...)) ;; case 1

(defmacro koo [x] ...) ;; case 2
```

`(:require-macros [foo.bar :refer [koo]])` not working for case 1, but  working for case 2

**Comment by anmonteiro** [comment]
This is the expected behavior. Lumo runs bootstrapped ClojureScript, so it never reads code under `:clj` reader conditionals.

**Comment by gfZeng** [comment]
@anmonteiro but `cljs-build` support it.

**Comment by anmonteiro** [comment]
I'm not sure what point you are making. `lein-cljsbuild` doesn't run under bootstrapped ClojureScript. Because it runs on the JVM it can expand ClojureScript macros that are written in Clojure (and consequently read the `:clj` reader conditionals).

In Lumo, however, there is no JVM, so you can't write macros in Clojure. You can write macros in ClojureScript and hide them under `:cljs` reader conditionals if you want (so the regular JVM ClojureScript doesn't see them).

**Comment by gfZeng** [comment]
Yeah, you are right.
But for now, there have many libs support both Clojure & ClojureScript that can use `JVM` build.

eg:
   - [datascript](https://github.com/tonsky/datascript)
   - [core.async](https://github.com/clojure/core.async)
