### ISSUE TITLE
Could not load file http://foo...

### ISSUE THREAD

**Issue by jkleiser** [anmonteiro/lumo#8]
When I do `lumo -h`, the main options include this:
`path                     Run a script from a file or resource`

Running a script from a (local) file works fine, but does "resource" imply the ability to run a script file on the net? When I tried this
```
lumo http://folk.uio.no/jkleiser/clojure/fib.cljs
```
then I got this:
```
#error {:message Could not load file http://folk.uio.no/jkleiser/clojure/fib.cljs, :data {}}
```
I'm using OSX 10.11.6 and node v6.5.0.

**Comment by anmonteiro** [comment]
This is interesting. 

By "resource" it means something in the classpath. Lumo emulates a (JVM) classpath in order to ease compatibility with Maven/Clojars artifacts. So the "file or resource" could either be local path in the filesystem or a resource in the classpath.

What you tried to do though, seems interesting, and I'll give it some more thought.

**Comment by anmonteiro** [comment]
I've given this a bit more thought and it's something we won't support for now. Loading "resources" from remote locations just introduces more complexity (support just http or ftp, etc as well? Where to look for dependencies of those resources?).
This is something that can easily be done with user code.
